MODEL_NAME: cnn_lstm_double_dqn

# Hyperparameters
BATCH_SIZE: 1024
GAMMA: 0.99
EPS_START: 1
EPS_END: 0.01
EPS_DECAY: 1000
TARGET_UPDATE: 100
MEMORY_SIZE: 1000000
LEARNING_RATE: 1e-4
NUM_EPISODES: 5000000
SEQUENCE_LENGTH: 5
HISTORY_LENGTH: 5
WEIGHT_DECAY: 1e-4
GRADIENT_CLIPPING: 1
OPTIMISE_EVERY_STEP: false
N_STEP: 6

# Logging params
LOG_EPISODE_INTERVAL: 10
VIDEO_EVERY_N_EPISODES: 25
SAVE_MODEL_INTERVAL: 100

# Game settings
INITIAL_LEVEL: 15
NUM_LIVES: 5

# Tetris Env Settings
ENV_ID: SimpleTetris-v0
RENDER_MODE: rgb_array
