MODEL_NAME: cnn_lstm_double_dqn_pretrained

# Hyperparameters
BATCH_SIZE: 512
GAMMA: 0.99
EPS_START: 1
EPS_END: 0.01
EPS_DECAY: 2000
TARGET_UPDATE: 20
MEMORY_SIZE: 10000000
LEARNING_RATE: 1e-4
NUM_EPISODES: 50000000000
SEQUENCE_LENGTH: 20
HISTORY_LENGTH: 20
WEIGHT_DECAY: 1e-4
GRADIENT_CLIPPING: 6
OPTIMISE_EVERY_STEP: false

# Replay Memory params
N_STEP: 10
PRIORITY_ALPHA: 0.6
PRIORITY_BETA: 0.4
PRIORITY_EPSILON: 1e-6

# Logging params
LOG_EPISODE_INTERVAL: 1000000000
VIDEO_EVERY_N_EPISODES: 25
SAVE_MODEL_INTERVAL: 500

# Game settings
INITIAL_LEVEL: 20
NUM_LIVES: 0

# Tetris Env Settings
ENV_ID: SimpleTetris-v0
RENDER_MODE: rgb_array
