MODEL_NAME: cnn_lstm_double_dqn

# Hyperparameters
BATCH_SIZE: 2048
GAMMA: 0.99
EPS_START: 1
EPS_END: 0.01
EPS_DECAY: 1000
TARGET_UPDATE: 25
MEMORY_SIZE: 10000000
LEARNING_RATE: 1e-4
NUM_EPISODES: 50000000000
SEQUENCE_LENGTH: 2
HISTORY_LENGTH: 2
WEIGHT_DECAY: 1e-4
GRADIENT_CLIPPING: 10000000
OPTIMISE_EVERY_STEP: false

# Replay Memory params
N_STEP: 3
PRIORITY_ALPHA: 0.6
PRIORITY_BETA_START: 0.4
PRIORITY_BETA_END: 1
PRIORITY_BETA_ANNEALING_STEPS: 100000
PRIORITY_EPSILON: 1e-6

# Logging params
LOG_EPISODE_INTERVAL: 1000000000
VIDEO_EVERY_N_EPISODES: 25
SAVE_MODEL_INTERVAL: 500

# Game settings
INITIAL_LEVEL: 20
NUM_LIVES: 0

# Tetris Env Settings
ENV_ID: SimpleTetris-v0
OBSERVATION_TYPE: rgb
RENDER_MODE: rgb_array
WIDTH: 10 # DEFAULT WIDTH OF THE PLAY FIELD
HEIGHT: 20 # DEFAULT HEIGHT OF THE PLAY FIELD THE USER CAN SEE
BUFFER_HEIGHT: 5 # 20 # DEFAULT BUFFER HEIGHT FOR THE PLAY FIELD

# If the hardware permits, a sliver of the 21st row is shown to aid players manipulate the active
#  piece in that area.
VISIBLE_HEIGHT: 21
