MODEL_NAME: cnn_lstm_dqn

# Hyperparameters
BATCH_SIZE: 512
GAMMA: 0.99
EPS_START: 1
EPS_END: 0.01
EPS_DECAY: 50000
TARGET_UPDATE: 10
MEMORY_SIZE: 1000000
LEARNING_RATE: 1e-4
NUM_EPISODES: 50000
SEQUENCE_LENGTH: 20
HISTORY_LENGTH: 20
WEIGHT_DECAY: 1e-4
GRADIENT_CLIPPING: 20

# Logging params
LOG_EPISODE_INTERVAL: 10
VIDEO_EVERY_N_EPISODES: 50

# Game settings
INITIAL_LEVEL: 1
NUM_LIVES: 0

# Tetris Env Settings
ENV_ID: SimpleTetris-v0
RENDER_MODE: rgb_array
