MODEL_NAME: cnn_lstm_double_dqn

# Hyperparameters
BATCH_SIZE: 2048
GAMMA: 0.99
EPS_START: 1
EPS_END: 0.01
EPS_DECAY: 100000
TARGET_UPDATE: 10
MEMORY_SIZE: 1000000
LEARNING_RATE: 1e-4
NUM_EPISODES: 50000000000
SEQUENCE_LENGTH: 3
HISTORY_LENGTH: 3
WEIGHT_DECAY: 1e-4
GRADIENT_CLIPPING: 6
OPTIMISE_EVERY_STEP: false
N_STEP: 4

# Logging params
LOG_EPISODE_INTERVAL: 10
VIDEO_EVERY_N_EPISODES: 100
SAVE_MODEL_INTERVAL: 100

# Game settings
INITIAL_LEVEL: 20
NUM_LIVES: 0

# Tetris Env Settings
ENV_ID: SimpleTetris-v0
RENDER_MODE: rgb_array
