MODEL_NAME: double_cnn_gru_double_dqn

# Hyperparameters
BATCH_SIZE: 3000
GAMMA: 0.99
EPS_START: 1
EPS_END: 0.01
EPS_DECAY: 10000
TARGET_UPDATE: 100
MEMORY_SIZE: 100000
LEARNING_RATE: 1e-5
NUM_EPISODES: 5000000
SEQUENCE_LENGTH: 10
HISTORY_LENGTH: 10
WEIGHT_DECAY: 1e-4
GRADIENT_CLIPPING: 6
OPTIMISE_EVERY_STEP: false

# Logging params
LOG_EPISODE_INTERVAL: 10
VIDEO_EVERY_N_EPISODES: 100
SAVE_MODEL_INTERVAL: 100

# Game settings
INITIAL_LEVEL: 1
NUM_LIVES: 0

# Tetris Env Settings
ENV_ID: SimpleTetris-v0
RENDER_MODE: rgb_array
